### ISSUE TITLE
Problem 2

### ISSUE THREAD

**Issue by MakeTheBrainHappy** [brucewangelvin/JavaLessons#2]
I have added an Array Problem for you. It also involves sorting. You will need to be able to compare the the elements in your first list to the elements in your second list in order to sort them correctly. You may also want to use a loop in order to get the correct order for all of the elements in your original list. 

This is a useful diagram for element lookup. The original array would have been declared as 
[https://study.com/cimages/multimages/16/java_add_to_array_manual.png](url)

int[] buckets = {15,32,7,105,78};

@brucewangelvin

**Comment by brucewangelvin** [comment]
I learned a lot about Arrays and I learned how to type in github

**Comment by MakeTheBrainHappy** [comment]
@brucewangelvin What exactly did you learn about arrays?

**Comment by brucewangelvin** [comment]
I learned how to declare an array
