### ISSUE TITLE
Minesweeper Code

### ISSUE THREAD

**Issue by MakeTheBrainHappy** [brucewangelvin/JavaLessons#3]
[: https://www.makethebrainhappy.com/2019/02/minesweeper-in-java.html](https://www.makethebrainhappy.com/2019/02/minesweeper-in-java.html)

**Comment by brucewangelvin** [comment]
I've figured out how to play Mine sweeper, It's pretty hard to play

**Comment by MakeTheBrainHappy** [comment]
Cool, I am sure that we can revisit the code at a later date in order to trace how it works. I'd want to review classes, objects and methods again before that point though. @brucewangelvin 

Lesson 4 awaits! 👍
